### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by mcszymist** [IAIDS/IAIDSWebsite#2]
AppName: home
Both
- [x] Banner
Not Logged In 
- [x] Summary
- [x] Event Button
- [x] Volunteer Text
- [x] Sign Up
Logged In 
- [x] Aesthetics

**Comment by mcszymist** [comment]
Header: Needs home link on left, Sign Up and login on right with About button.

Footer need a copyright footer at least

**Comment by mcszymist** [comment]
For the landing: We need to brainstorm.

**Comment by acheeseye** [comment]
for the landing I think a big chunk should be "nearby opportunities" if the user is logged in

**Comment by acheeseye** [comment]
also should we force the user to log in before reaching the landing?

**Comment by mcszymist** [comment]
I like the nearby opportunities idea
For force logging in I dont think so we should have like a welcome page.

**Comment by mcszymist** [comment]
Both
- [ ] Banner
Not Logged In 
- [ ] Summary
- [ ] Event Button
- [ ] Volunteer Text
- [ ] Sign Up
Logged In 
- [ ] option: 1stStrike Option system
