### ISSUE TITLE
About link appears in 2 places

### ISSUE THREAD

**Issue by acheeseye** [IAIDS/IAIDSWebsite#38]
Having two links to an about page may be redundant, but is up to group opinion. If O.K. then we can resolve.

**Comment by FromAlaska** [comment]
I've added the about link to only show up at the home page. Would that be a good fix?

**Comment by acheeseye** [comment]
oh--I mean the two places as in the top nav bar and the footer. I think we may take out the footer unless we figure out what information we can put there

**Comment by acheeseye** [comment]
I'll put that into "pending questions"
