### ISSUE TITLE
allow an onclick event to store clicked event into "Event vols"

### ISSUE THREAD

**Issue by acheeseye** [IAIDS/IAIDSWebsite#82]
- [ ] read current user
- [ ] read clicked event
- [ ] request store user + event into Event vols
- [ ] deny request if such row already exists
- [ ] show denied request (such as greyed out button)

duplicate issue -- already developed

**Comment by mcszymist** [comment]
Im not sure what you mean by this so I moved this to discussion because it might already do this.
